version: '3.8'

services:
  ollama:
    env_file: .env
    image: ollama/ollama
    ports:
      - "11438:11434"  # внешний порт 11438 -> внутренний 11434
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-network-cust

volumes:
  ollama_data:

networks:
  ai-network-cust:
    driver: bridge
