version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11439:11434"
    volumes:
      - ollama_data:/root/.ollama
    # Для GPU добавьте:
    deploy:
      resources:
        reservations:
           devices:
             - driver: nvidia
               #count: 1
               capabilities: [gpu]

  app:
    build: .
    depends_on:
      ollama:
        condition: service_started
    volumes:
      - ./:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
    command: sh -c "sleep 20 && python test.py"  # Даем Ollama время на запуск

volumes:
  ollama_data: